name: Trigger Buildkite PR
on:
  push:
    paths:
      - "bar-service/*"
    branches:
      - "*"
      - "*/*"
      - "!master"

jobs:
  build:
    name: Bar Service Pull request
    runs-on: ubuntu-latest
    env:
      BUILDKITE_API_ACCESS_TOKEN: ${{ secrets.BUILDKITE_API_ACCESS_TOKEN }}
      MESSAGE: ":github: ${{github.event.head_commit.message}}"
    steps:
      - name: Bar service pull request
        uses: buildkite/trigger-pipeline-action@v1.2.0
        env:
          PIPELINE: adikari/bar-service-pull-request
