name: Trigger Buildkite PR
on:
  push:
    branches:
      - '*'
      - '*/*'
      - "!master"

jobs:
  build:
    name: Pull request pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Trigger pipeline
        uses: buildkite/trigger-pipeline-action@v1.2.0
        env:
          PIPELINE: adikari/pull-request
          MESSAGE: ":github: ${{github.event.head_commit.message}}"
          BUILDKITE_API_ACCESS_TOKEN: ${{ secrets.BUILDKITE_API_ACCESS_TOKEN }}
